docs(GiniPayBankSDK)
gini/gini-pay-bank-sdk-ios pull request #36
Opened 2021-11-11 16:54 UTC by zladzeyka

* Add deprecation notice and link to the migration guide.

PIA-1982

2021-11-12 10:27 UTC, a-szotyori approved these changes

2021-11-12 10:31 UTC, a-szotyori requested changes

2021-11-12 10:31 UTC, a-szotyori commented on README.md
> + [Gini Bank SDK](https://github.com/gini/bank-sdk-ios/.
Link format is incorrect: missing closing `)`.
```suggestion
 [Gini Bank SDK](https://github.com/gini/bank-sdk-ios/).
```

2021-11-12 10:31 UTC, a-szotyori commented on Documentation/sections/Documentation.md
> + [Gini Bank SDK](https://github.com/gini/bank-sdk-ios/.
Link format is incorrect: missing closing `)`.
```suggestion
 [Gini Bank SDK](https://github.com/gini/bank-sdk-ios/).
```

2021-11-17 12:25 UTC, zladzeyka commented
I've verified the link on the migration guide.

2021-11-17 13:01 UTC, a-szotyori approved these changes
👍

2021-11-18 09:41 UTC, merged